# Generated by Django 4.1.3 on 2022-12-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
