# Generated by Django 4.1.3 on 2022-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0007_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\metod\\Documents\\Softuni\\Web Frameworks\\demo_project\\static/images'),
        ),
    ]
